version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    container_name: prisma_postgresql
    ports:
      - '5433:5432'
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '5555:5555'
    env_file:
      - .env.production # Загружаем переменные окружения из env.production
    environment:
      DATABASE_URL: ${DATABASE_URL} # Указываем переменную DATABASE_URL из .env.production
    depends_on:
      - db

volumes:
  postgres_data:
